# <font color=green> PYTHON PARA DATA SCIENCE - PANDAS
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares.
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assundo é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [ ]:
!python -V

Python 3.6.8

# 1.3 Trabalhando com dados

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html

In [ ]:
import pandas as pd
# pd.set_option('display.max_rows', 10)
# pd.set_option('display.max_columns', 1000)

In [ ]:
dataset = pd.read_csv('db.csv', sep = ';')

In [ ]:
dataset

                      Nome  ...      Valor
0            Jetta Variant  ...   88078.64
1                   Passat  ...  106161.94
2                 Crossfox  ...   72832.16
3                      DS5  ...  124549.07
4         Aston Martin DB4  ...   92612.10
..                     ...  ...        ...
253           Phantom 2013  ...   51759.58
254  Cadillac Ciel concept  ...   51667.06
255             Classe GLK  ...   68934.03
256       Aston Martin DB5  ...  122110.90
257                  Macan  ...   90381.47

[258 rows x 7 columns]

In [ ]:
dataset.dtypes

Nome              object
Motor             object
Ano                int64
Quilometragem    float64
Zero_km             bool
Acessórios        object
Valor            float64
dtype: object

In [ ]:
dataset[['Quilometragem', 'Valor']].describe()

       Quilometragem          Valor
count     197.000000     258.000000
mean    58278.421320   98960.513101
std     35836.733259   29811.932305
min       107.000000   50742.100000
25%     27505.000000   70743.512500
50%     55083.000000   97724.380000
75%     90495.000000  124633.302500
max    119945.000000  149489.920000

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
Nome             258 non-null object
Motor            258 non-null object
Ano              258 non-null int64
Quilometragem    197 non-null float64
Zero_km          258 non-null bool
Acessórios       258 non-null object
Valor            258 non-null float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

# <font color=green> 2. TRABALHANDO COM TUPLAS
---

# 2.1 Criando tuplas

Tuplas são sequências imutáveis que são utilizadas para armazenar coleções de itens, geralmente heterogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de parênteses: ( )
- Utilizando uma vírgula à direita: x,
- Utilizando um par de parênteses com itens separados por vírgulas: ( x, y, z )
- Utilizando: tuple() ou tuple(iterador)
```

In [ ]:
()

()

In [ ]:
1, 2, 3

(1, 2, 3)

In [ ]:
nome = 'Passat'
valor = 153000
(nome, valor)

('Passat', 153000)

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [ ]:
type(nomes_carros)

tuple

# 2.2 Seleções em tuplas

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [ ]:
nomes_carros[0]

'Jetta Variant'

In [ ]:
nomes_carros[1]

'Passat'

In [ ]:
nomes_carros[-1]

'DS5'

In [ ]:
nomes_carros[1:3]

('Passat', 'Crossfox')

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5', ('Fusca', 'Gol', 'C4'))
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5', ('Fusca', 'Gol', 'C4'))

In [ ]:
nomes_carros[-1]

('Fusca', 'Gol', 'C4')

In [ ]:
nomes_carros[-1][1]

'Gol'

# 2.3 Iterando em tuplas

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [ ]:
for item in nomes_carros:
  print(item)

Jetta Variant
Passat
Crossfox
DS5

### Desempacotamento de tuplas

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [ ]:
carro_1, carro_2, carro_3, carro_4 = nomes_carros

In [ ]:
carro_1

'Jetta Variant'

In [ ]:
carro_2

'Passat'

In [ ]:
carro_3

'Crossfox'

In [ ]:
carro_4

'DS5'

In [ ]:
_, A, _, B = nomes_carros

In [ ]:
A

'Passat'

In [ ]:
B

'DS5'

In [ ]:
_, C, *_ = nomes_carros

In [ ]:
C

'Passat'

## *zip()*

https://docs.python.org/3.6/library/functions.html#zip

In [ ]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
carros

['Jetta Variant', 'Passat', 'Crossfox', 'DS5']

In [ ]:
valores = [88078.64, 106161.94, 72832.16, 124549.07]
valores

[88078.64, 106161.94, 72832.16, 124549.07]

In [ ]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64),
 ('Passat', 106161.94),
 ('Crossfox', 72832.16),
 ('DS5', 124549.07)]

In [ ]:
for item in zip(carros, valores):
  print(item)

('Jetta Variant', 88078.64)
('Passat', 106161.94)
('Crossfox', 72832.16)
('DS5', 124549.07)

In [ ]:
for carro, valor in zip(carros, valores):
  print(carro, valor)

Jetta Variant 88078.64
Passat 106161.94
Crossfox 72832.16
DS5 124549.07

In [ ]:
for carro, valor in zip(carros, valores):
  if(valor > 100000):
    print(carro)

Passat
DS5

# <font color=green> 3. TRABALHANDO COM DICIONÁRIOS
---

# 3.1 Criando dicionários

Listas são coleções sequenciais, isto é, os itens destas sequências estão ordenados e utilizam índices (números inteiros) para acessar os valores.

Os dicionários são coleções um pouco diferentes. São estruturas de dados que representam um tipo de mapeamento. Mapeamentos são coleções de associações entre pares de valores onde o primeiro elemento do par é conhecido como chave (*key*) e o segundo como valor (*value*).

```
dicionario = {key_1: value_1, key_2: value_2, ..., key_n: value_n}
```

https://docs.python.org/3.6/library/stdtypes.html#typesmapping

In [ ]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [ ]:
valores = [88078.64, 106161.94, 72832.16]
valores

[88078.64, 106161.94, 72832.16]

In [ ]:
carros.index('Passat')

1

In [ ]:
valores[carros.index('Passat')]

106161.94

In [ ]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [ ]:
type(dados)

dict

### Criando dicionários com *zip()*

In [ ]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64), ('Passat', 106161.94), ('Crossfox', 72832.16)]

In [ ]:
dados = dict(zip(carros, valores))
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

# 3.2 Operações com dicionários

In [ ]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

## *dict[ key ]*

Retorna o valor correspondente à chave (*key*) no dicionário.

In [ ]:
dados['Passat']

106161.94

## *key in dict*

Retorna **True** se a chave (*key*) for encontrada no dicionário.

In [ ]:
'Passat' in dados

True

In [ ]:
'Fusca' in dados

False

In [ ]:
'Fusca' not in dados

True

## *len(dict)*

Retorna o número de itens do dicionário.

In [ ]:
len(dados)

3

## *dict[ key ] = value*

Inclui um item ao dicionário.

In [ ]:
dados['DS5'] = 124549.07

In [ ]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

## *del dict[ key ]*

Remove o item de chave (*key*) do dicionário.

In [ ]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

In [ ]:
del dados['Passat']
dados

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

# 3.3 Métodos de dicionários

https://docs.python.org/3.6/tutorial/datastructures.html#dictionaries

https://docs.python.org/3.6/library/stdtypes.html#typesmapping

## *dict.update()*

Atualiza o dicionário.

In [ ]:
dados

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

In [ ]:
dados.update({'Passat': 106161.94})
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

In [ ]:
dados.update({'Passat': 106161.95, 'Fusca': 150000})
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

## *dict.copy()*

Cria uma cópia do dicionário.

In [ ]:
dadosCopy = dados.copy()

In [ ]:
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [ ]:
del dadosCopy['Fusca']
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [ ]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

## *dict.pop(key[, default ])*

Se a chave for encontrada no dicionário, o item é removido e seu valor é retornado. Caso contrário, o valor especificado como *default* é retornado. Se o valor *default* não for fornecido e a chave não for encontrada no dicionário um erro será gerado.

In [ ]:
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [ ]:
dadosCopy.pop('Passat')

106161.95

In [ ]:
dadosCopy

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

In [ ]:
# dadosCopy.pop('Passat')

In [ ]:
dadosCopy.pop('Passat', 'Chave não encontrada')

'Chave não encontrada'

In [ ]:
dadosCopy.pop('DS5', 'Chave não encontrada')

124549.07

In [ ]:
dadosCopy

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64}

## *dict.clear()*

Remove todos os itens do dicionário.

In [ ]:
dadosCopy.clear()

In [ ]:
dadosCopy

{}

# 3.4 Iterando em dicionários

In [ ]:
dados = {'Crossfox': 72832.16, 'DS5': 124549.07, 'Fusca': 150000, 'Jetta Variant': 88078.64, 'Passat': 106161.95}
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

## *dict.keys()*

Retorna uma lista contendo as chaves (*keys*) do dicionário.

In [ ]:
dados.keys()

dict_keys(['Crossfox', 'DS5', 'Fusca', 'Jetta Variant', 'Passat'])

In [ ]:
for key in dados.keys():
  print(dados[key])

72832.16
124549.07
150000
88078.64
106161.95

## *dict.values()*

Retorna uma lista com todos os valores (*values*) do dicionário.

In [ ]:
dados.values()

dict_values([72832.16, 124549.07, 150000, 88078.64, 106161.95])

## *dict.items()*

Retorna uma lista contendo uma tupla para cada par chave-valor (*key-value*) do dicionário.

In [ ]:
dados.items()

dict_items([('Crossfox', 72832.16), ('DS5', 124549.07), ('Fusca', 150000), ('Jetta Variant', 88078.64), ('Passat', 106161.95)])

In [ ]:
for item in dados.items():
  print(item)

('Crossfox', 72832.16)
('DS5', 124549.07)
('Fusca', 150000)
('Jetta Variant', 88078.64)
('Passat', 106161.95)

In [ ]:
for key, value in dados.items():
  print(key, value)

Crossfox 72832.16
DS5 124549.07
Fusca 150000
Jetta Variant 88078.64
Passat 106161.95

In [ ]:
for key, value in dados.items():
  if(value > 100000):
    print(key)

DS5
Fusca
Passat

# <font color=green> 4. FUNÇÕES
---
    
Funções são unidades de código reutilizáveis que realizam uma tarefa específica, podem receber alguma entrada e também podem retornar alguma resultado.

# 4.1 Built-in function

A linguagem Python possui várias funções integradas que estão sempre acessíveis. Algumas já utilizamos em nosso treinamento: type(), print(), zip(), len(), set() etc.

https://docs.python.org/3.6/library/functions.html

In [ ]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [ ]:
valores = []
for valor in dados.values():
  valores.append(valor)
valores

[88078.64, 106161.94, 72832.16]

In [ ]:
soma = 0
for valor in dados.values():
  soma += valor
soma

267072.74

In [ ]:
list(dados.values())

[88078.64, 106161.94, 72832.16]

In [ ]:
sum(dados.values())

267072.74

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

In [ ]:
print?

# 4.2 Definindo funções sem e com parâmetros

### Funções sem parâmetros

#### Formato padrão

```
def <nome>():
    <instruções>
```

In [ ]:
def media():
  valor = (1 + 2 + 3) / 3
  print(valor)

In [ ]:
media()

2.0

### Funções com parâmetros

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
```

In [ ]:
def media(number_1, number_2, number_3):
  valor = (number_1 + number_2 + number_3) / 3
  print(valor)

In [ ]:
media(1, 2, 3)

2.0

In [ ]:
media(23, 45, 67)

45.0

In [ ]:
def media(lista):
  valor = sum(lista) / len(lista)
  print(valor)

In [ ]:
resultado = media([1, 2, 3, 4, 5, 6, 7, 8, 9])

5.0

In [ ]:
resultado

In [ ]:
type(resultado)

NoneType

# 4.3 Definindo funções que retornam valores

### Funções que retornam um valor

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
    return <resultado>
```

In [ ]:
def media(lista):
  valor = sum(lista) / len(lista)
  return valor

In [ ]:
media([1, 2, 3, 4, 5, 6, 7, 8])

4.5

In [ ]:
resultado = media([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
resultado

4.5

### Funções que retornam mais de um valor

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
    return (<resultado_1>, <resultado_2>, ..., <resultado_n>)
```

In [ ]:
def media(lista):
  valor = sum(lista) / len(lista)
  return (valor, len(lista))

In [ ]:
media([1, 2, 3, 4, 5, 6, 7, 8, 9])

(5.0, 9)

In [ ]:
resultado, n = media([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
resultado

5.0

In [ ]:
n

9

# <font color=green> 5. PANDAS BÁSICO
---

**versão: 0.25.2**
  
Pandas é uma ferramenta de manipulação de dados de alto nível, construída com base no pacote Numpy. O pacote pandas possui estruturas de dados bastante interessantes para manipulação de dados e por isso é muito utilizado por cientistas de dados.


## Estruturas de Dados

### Series

Series são arrays unidimensionais rotulados capazes de armazenar qualquer tipo de dado. Os rótulos das linhas são chamados de **index**. A forma básica de criação de uma Series é a seguinte:


```
    s = pd.Series(dados, index = index)
```

O argumento *dados* pode ser um dicionário, uma lista, um array Numpy ou uma constante.

### DataFrames

DataFrame é uma estrutura de dados tabular bidimensional com rótulos nas linha e colunas. Como a Series, os DataFrames são capazes de armazenar qualquer tipo de dados.


```
    df = pd.DataFrame(dados, index = index, columns = columns)
```

O argumento *dados* pode ser um dicionário, uma lista, um array Numpy, uma Series e outro DataFrame.

**Documentação:** https://pandas.pydata.org/pandas-docs/version/0.25/

# 5.1 Estruturas de dados

In [ ]:
import pandas as pd

### Criando uma Series a partir de uma lista

In [ ]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [ ]:
pd.Series(carros)

0    Jetta Variant
1           Passat
2         Crossfox
dtype: object

### Criando um DataFrame a partir de uma lista de dicionários

In [ ]:
dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72832.16}
]
dados

[{'Nome': 'Jetta Variant',
  'Motor': 'Motor 4.0 Turbo',
  'Ano': 2003,
  'Quilometragem': 44410.0,
  'Zero_km': False,
  'Valor': 88078.64},
 {'Nome': 'Passat',
  'Motor': 'Motor Diesel',
  'Ano': 1991,
  'Quilometragem': 5712.0,
  'Zero_km': False,
  'Valor': 106161.94},
 {'Nome': 'Crossfox',
  'Motor': 'Motor Diesel V8',
  'Ano': 1990,
  'Quilometragem': 37123.0,
  'Zero_km': False,
  'Valor': 72832.16}]

In [ ]:
ds = pd.DataFrame(dados)
ds

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

In [ ]:
ds[['Nome','Ano','Quilometragem','Valor']]

            Nome   Ano  Quilometragem      Valor
0  Jetta Variant  2003        44410.0   88078.64
1         Passat  1991         5712.0  106161.94
2       Crossfox  1990        37123.0   72832.16

### Criando um DataFrame a partir de um dicionário

In [ ]:
import pandas as pd
dados = {
    'Nome': ['Jetta Variant', 'Passat', 'Crossfox'],
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Ano': [2003, 1991, 1990],
    'Quilometragem': [44410.0, 5712.0, 37123.0],
    'Zero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72832.16]
}

In [ ]:
ds = pd.DataFrame(dados)

### Criando um DataFrame a partir de uma arquivo externo

In [ ]:
ds = pd.read_csv('db.csv',sep=';', index_col = 0)

In [ ]:
ds

                                       Motor  ...      Valor
Nome                                          ...
Jetta Variant                Motor 4.0 Turbo  ...   88078.64
Passat                          Motor Diesel  ...  106161.94
Crossfox                     Motor Diesel V8  ...   72832.16
DS5                          Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4             Motor 2.4 Turbo  ...   92612.10
...                                      ...  ...        ...
Phantom 2013                        Motor V8  ...   51759.58
Cadillac Ciel concept               Motor V8  ...   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo  ...   68934.03
Aston Martin DB5                Motor Diesel  ...  122110.90
Macan                        Motor Diesel V6  ...   90381.47

[258 rows x 6 columns]

# 5.2 Seleções com DataFrames

### Selecionando colunas

In [ ]:
ds = pd.read_csv('db.csv',sep=';', index_col = 0)
ds

                                       Motor  ...      Valor
Nome                                          ...
Jetta Variant                Motor 4.0 Turbo  ...   88078.64
Passat                          Motor Diesel  ...  106161.94
Crossfox                     Motor Diesel V8  ...   72832.16
DS5                          Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4             Motor 2.4 Turbo  ...   92612.10
...                                      ...  ...        ...
Phantom 2013                        Motor V8  ...   51759.58
Cadillac Ciel concept               Motor V8  ...   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo  ...   68934.03
Aston Martin DB5                Motor Diesel  ...  122110.90
Macan                        Motor Diesel V6  ...   90381.47

[258 rows x 6 columns]

In [ ]:
ds.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [ ]:
ds['Valor']

0     88000.0
1    106000.0
2     72000.0
3     89000.0
4     32000.0
Name: Valor, dtype: float64

In [ ]:
dados = {
    'Nome': ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'],
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

ds = pd.DataFrame(dados)
ds[['Valor']]

      Valor
0   88000.0
1  106000.0
2   72000.0
3   89000.0
4   32000.0

### Selecionando linhas - [ i : j ]

<font color=red>**Observação:**</font> A indexação tem origem no zero e nos fatiamentos (*slices*) a linha com índice i é **incluída** e a linha com índice j **não é incluída** no resultado.

In [ ]:
ds = pd.read_csv('db.csv',sep=';', index_col = 0)
ds
ds[:4]

                         Motor  ...      Valor
Nome                            ...
Jetta Variant  Motor 4.0 Turbo  ...   88078.64
Passat            Motor Diesel  ...  106161.94
Crossfox       Motor Diesel V8  ...   72832.16
DS5            Motor 2.4 Turbo  ...  124549.07

[4 rows x 6 columns]

### Utilizando .loc para seleções

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou uma matriz booleana.

In [ ]:
ds

                                       Motor  ...      Valor
Nome                                          ...
Jetta Variant                Motor 4.0 Turbo  ...   88078.64
Passat                          Motor Diesel  ...  106161.94
Crossfox                     Motor Diesel V8  ...   72832.16
DS5                          Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4             Motor 2.4 Turbo  ...   92612.10
...                                      ...  ...        ...
Phantom 2013                        Motor V8  ...   51759.58
Cadillac Ciel concept               Motor V8  ...   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo  ...   68934.03
Aston Martin DB5                Motor Diesel  ...  122110.90
Macan                        Motor Diesel V6  ...   90381.47

[258 rows x 6 columns]

In [ ]:
ds.loc[['Jetta','Crossfox']]

                          Motor  ...      Valor
Nome                             ...
Jetta     Motor 5.0 V8 Bi-Turbo  ...  140934.60
Crossfox        Motor Diesel V8  ...   72832.16

[2 rows x 6 columns]

In [ ]:
ds.loc[['Jetta','Crossfox'],['Motor', 'Valor']]

                          Motor      Valor
Nome
Jetta     Motor 5.0 V8 Bi-Turbo  140934.60
Crossfox        Motor Diesel V8   72832.16

In [ ]:
ds.loc[:,['Motor', 'Valor']]

                                       Motor      Valor
Nome
Jetta Variant                Motor 4.0 Turbo   88078.64
Passat                          Motor Diesel  106161.94
Crossfox                     Motor Diesel V8   72832.16
DS5                          Motor 2.4 Turbo  124549.07
Aston Martin DB4             Motor 2.4 Turbo   92612.10
...                                      ...        ...
Phantom 2013                        Motor V8   51759.58
Cadillac Ciel concept               Motor V8   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo   68934.03
Aston Martin DB5                Motor Diesel  122110.90
Macan                        Motor Diesel V6   90381.47

[258 rows x 2 columns]

### Utilizando .iloc para seleções

<font color=red>**Observação:**</font> Seleciona com base nos índices, ou seja, se baseia na posição das informações.

In [ ]:
ds.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [ ]:
ds.iloc[[1]]

               Motor  ...      Valor
Nome                  ...
Passat  Motor Diesel  ...  106161.94

[1 rows x 6 columns]

In [ ]:
ds.iloc[1:4]

                    Motor  ...      Valor
Nome                       ...
Passat       Motor Diesel  ...  106161.94
Crossfox  Motor Diesel V8  ...   72832.16
DS5       Motor 2.4 Turbo  ...  124549.07

[3 rows x 6 columns]

In [ ]:
ds.iloc[1:4,[0,5,1]]

                    Motor      Valor   Ano
Nome
Passat       Motor Diesel  106161.94  1991
Crossfox  Motor Diesel V8   72832.16  1990
DS5       Motor 2.4 Turbo  124549.07  2019

In [ ]:
ds.iloc[[2,4,6],[5,3]]

                     Valor  Zero_km
Nome
Crossfox          72832.16    False
Aston Martin DB4  92612.10    False
A5                56445.20     True

In [ ]:
dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])
dataset

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5             Motor 2.0  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

# 5.3 Queries com DataFrames

### Utilizando o método query

# 5.4 Iterando com DataFrames

# 5.5 Tratamento de dados

In [ ]:
import pandas as pd
ds = pd.read_csv('db.csv',sep=';', index_col = 0)
ds.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, Jetta Variant to Macan
Data columns (total 6 columns):
Motor            258 non-null object
Ano              258 non-null int64
Quilometragem    197 non-null float64
Zero_km          258 non-null bool
Acessórios       258 non-null object
Valor            258 non-null float64
dtypes: bool(1), float64(2), int64(1), object(2)
memory usage: 22.3+ KB

In [ ]:
ds.Quilometragem.isna()

Nome
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                       True
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
Name: Quilometragem, Length: 258, dtype: bool

In [ ]:
ds[ds.Quilometragem.isna()]

                                Motor  ...      Valor
Nome                                   ...
DS5                   Motor 2.4 Turbo  ...  124549.07
A5                    Motor 4.0 Turbo  ...   56445.20
J5                           Motor V6  ...   53183.38
A3                       Motor 1.0 8v  ...   88552.39
Série 1 M                    Motor V8  ...   94564.40
...                               ...  ...        ...
Lamborghini Reventón  Motor 4.0 Turbo  ...   67664.86
Benni Mini                   Motor V8  ...  126247.84
Uno                   Motor Diesel V6  ...  128852.21
Santa Fe                Motor 3.0 32v  ...  129415.33
XC60                  Motor 4.0 Turbo  ...   77675.79

[61 rows x 6 columns]

In [ ]:
ds.fillna(0,inplace=True)

In [ ]:
ds.query('Zero_km == True')

In [ ]:
ds.dropna(subset = ['Quilometragem'], inplace=True)

In [ ]:
ds

                                       Motor  ...      Valor
Nome                                          ...
Jetta Variant                Motor 4.0 Turbo  ...   88078.64
Passat                          Motor Diesel  ...  106161.94
Crossfox                     Motor Diesel V8  ...   72832.16
Aston Martin DB4             Motor 2.4 Turbo  ...   92612.10
Palio Weekend                  Motor 1.8 16v  ...   97497.73
...                                      ...  ...        ...
Phantom 2013                        Motor V8  ...   51759.58
Cadillac Ciel concept               Motor V8  ...   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo  ...   68934.03
Aston Martin DB5                Motor Diesel  ...  122110.90
Macan                        Motor Diesel V6  ...   90381.47

[197 rows x 6 columns]